general.import = [
"~/.config/alacritty/themes/tokyo_night_enhanced.toml"
]


[font]

normal.family = "Hack Nerd Font"
bold.family = "Hack Nerd Font"
italic.family = "Hack Nerd Font"
bold_italic.family = "Hack Nerd Font"

